<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Feature\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IdIdentifyApp.Common\IdIdentifyApp.Common.csproj" />
  </ItemGroup>

</Project>
